package com.hermexapp.android.network

/**
 * Paths verified against the pinned upstream source (`.codex-tmp/hermes-webui`,
 * `api/routes.py` + `api/auth.py`) — never invented (root AGENTS.md hard rule #1).
 * Mirrors the iOS `Endpoint` enum; grows one entry per endpoint as phases land.
 */
enum class Endpoint(val path: String) {
    HEALTH("/health"),
    AUTH_STATUS("/api/auth/status"),
    LOGIN("/api/auth/login"),
    LOGOUT("/api/auth/logout"),
    SESSIONS("/api/sessions"),
    SESSIONS_SEARCH("/api/sessions/search"),
    SESSION("/api/session"),
    SESSION_STATUS("/api/session/status"),
    SESSION_NEW("/api/session/new"),
    SESSION_RENAME("/api/session/rename"),
    SESSION_DELETE("/api/session/delete"),
    SESSION_PIN("/api/session/pin"),
    SESSION_ARCHIVE("/api/session/archive"),
    CHAT_START("/api/chat/start"),
    CHAT_STREAM("/api/chat/stream"),
    CHAT_CANCEL("/api/chat/cancel"),
    CHAT_STEER("/api/chat/steer"),
    MODELS("/api/models"),
    COMMANDS("/api/commands"),
    DEFAULT_MODEL("/api/default-model"),
    PROFILES("/api/profiles"),
    PROFILE_SWITCH("/api/profile/switch"),
    WORKSPACES("/api/workspaces"),
    SETTINGS("/api/settings"),
    UPLOAD("/api/upload"),
    DIRECTORY_LIST("/api/list"),
    FILE("/api/file"),
    GIT_INFO("/api/git-info"),
    GIT_STATUS("/api/git/status"),
    GIT_BRANCHES("/api/git/branches"),
    GIT_DIFF("/api/git/diff"),
    CRONS("/api/crons"),
    CRON_RUN("/api/crons/run"),
    CRON_PAUSE("/api/crons/pause"),
    CRON_RESUME("/api/crons/resume"),
    CRON_DELETE("/api/crons/delete"),
    SKILLS("/api/skills"),
    SKILL_CONTENT("/api/skills/content"),
    MEMORY("/api/memory"),
    INSIGHTS("/api/insights"),
}
