import java.util.Properties
import java.io.FileInputStream
import java.io.File as JFile

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
}

// --- Release-signing credential resolution --------------------------------
//
// Production keystore credentials MUST NOT live in git. Resolution order:
//   1. Environment variables (set by CI / the operator's shell):
//        HERMEX_RELEASE_STORE_FILE
//        HERMEX_RELEASE_STORE_PASSWORD
//        HERMEX_RELEASE_KEY_ALIAS
//        HERMEX_RELEASE_KEY_PASSWORD
//   2. The un-tracked `android/local.properties` file:
//        hermex.release.storeFile=...
//        hermex.release.storePassword=...
//        hermex.release.keyAlias=...
//        hermex.release.keyPassword=...
//
// If neither is set we still build a release APK, but it will be UNSIGNED.
// The CI release workflow (`.github/workflows/android-release.yml`) sets
// the env vars from GitHub Secrets so a signed APK is what ships from
// the tag pipeline.
//
// To generate a new keystore locally:
//   keytool -genkey -v -keystore ~/keystores/hermex-release.jks \
//           -keyalg RSA -keysize 2048 -validity 10000 \
//           -alias hermex-release -dname "CN=JKP,O=Hermex,C=US"
//
data class ReleaseSigning(
    val storeFile: String,
    val storePassword: String,
    val keyAlias: String,
    val keyPassword: String,
)

fun resolveReleaseSigning(): ReleaseSigning? {
    val env = System.getenv()
    val envStoreFile = env["HERMEX_RELEASE_STORE_FILE"]
    val envStorePwd = env["HERMEX_RELEASE_STORE_PASSWORD"]
    val envKeyAlias = env["HERMEX_RELEASE_KEY_ALIAS"]
    val envKeyPwd = env["HERMEX_RELEASE_KEY_PASSWORD"]
    if (envStoreFile != null && envStorePwd != null &&
        envKeyAlias != null && envKeyPwd != null
    ) {
        return ReleaseSigning(envStoreFile, envStorePwd, envKeyAlias, envKeyPwd)
    }

    val localProps = Properties()
    val f = rootProject.file("local.properties")
    if (f.exists()) {
        FileInputStream(f).use { localProps.load(it) }
    }
    val localStoreFile = localProps.getProperty("hermex.release.storeFile")
    val localStorePwd = localProps.getProperty("hermex.release.storePassword")
    val localKeyAlias = localProps.getProperty("hermex.release.keyAlias")
    val localKeyPwd = localProps.getProperty("hermex.release.keyPassword")
    if (localStoreFile != null && localStorePwd != null &&
        localKeyAlias != null && localKeyPwd != null
    ) {
        return ReleaseSigning(localStoreFile, localStorePwd, localKeyAlias, localKeyPwd)
    }
    return null
}

android {
    namespace = "com.hermexapp.android"
    compileSdk = 35

    defaultConfig {
        // Provisional application id — revisit before the first Play upload
        // (Android port plan §6, branding open question).
        applicationId = "com.hermexapp.android"
        minSdk = 26
        targetSdk = 35
        versionCode = 13
        versionName = "0.6.0"
    }

    buildTypes {
        getByName("debug") {
            // Default debug signing (auto-generated by AGP ~/.android/debug.keystore).
            isMinifyEnabled = false
        }
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            // Wire up release signing if creds are available. Without creds
            // we fall through to the AGP default (no signing), so the build
            // still succeeds locally but the operator MUST configure
            // creds before shipping. The warning below makes this visible.
            val sig = resolveReleaseSigning()
            if (sig != null) {
                // Resolve the keystore path. Absolute paths are used as-is;
                // relative paths are resolved against the android/ subproject
                // directory (where local.properties lives).
                val raw = JFile(sig.storeFile)
                val keystore = if (raw.isAbsolute) raw
                               else JFile(project.projectDir, sig.storeFile)
                signingConfig = signingConfigs.create("release").apply {
                    storeFile = keystore
                    storePassword = sig.storePassword
                    keyAlias = sig.keyAlias
                    keyPassword = sig.keyPassword
                }
            } else {
                logger.warn("Hermex release build is UNSIGNED - set HERMEX_RELEASE_STORE_FILE/PASSWORD/KEY_ALIAS/KEY_PASSWORD env vars or android/local.properties entries. See app/build.gradle.kts.")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    packaging {
        resources {
            excludes += setOf(
                "/META-INF/{AL2.0,LGPL2.1}",
                "/META-INF/DEPENDENCIES",
                "/META-INF/LICENSE",
                "/META-INF/LICENSE.txt",
                "/META-INF/NOTICE",
                "/META-INF/NOTICE.txt",
            )
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.okhttp)
    implementation(libs.okhttp.sse)
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    // 6.6 QR camera pairing (operator-approved 2026-07-21). CameraX drives the
    // preview + frame analysis; ZXing decodes the QR payload locally.
    implementation(libs.androidx.camera.core)
    implementation(libs.androidx.camera.camera2)
    implementation(libs.androidx.camera.lifecycle)
    implementation(libs.androidx.camera.view)
    implementation(libs.zxing.core)

    testImplementation(libs.junit)
    testImplementation(libs.okhttp.mockwebserver)
    testImplementation(libs.kotlinx.coroutines.test)

    debugImplementation(libs.androidx.compose.ui.tooling)
}
